fix building version 3.31 by using autoconf/libtools
conda-forge/healpix_cxx-feedstock pull request #15
Opened 2022-01-05 07:19 UTC by mwittgen

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-01-05 07:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.


I do have some suggestions for making it better though...


For **recipe**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2022-01-05 07:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-01-05 11:50 UTC, beckermr reviewed
See the PR for 3.8X. We should match that.

2022-01-05 15:34 UTC, mwittgen commented
> See the PR for 3.8X. We should match that.

This PR has some weird build recipe as well like patching the config.stat with sed and creating the shared lib from the static libs.
Unfortunately the whole upstream package build is not consistent and varies from version to version.

2022-01-05 15:47 UTC, beckermr commented on recipe/build.sh
I don't see this:

```
if [ "$(uname)" == "Darwin" ]; then

    ${CXX} -fPIC -shared -o $PREFIX/lib/libhealpix_cxx.dylib -Wl,-force_load $PREFIX/lib/libhealpix_cxx.a -Wl,-force_load $PREFIX/lib/libsharp.a -lomp -lcfitsio ${CXXFLAGS} ${LDFLAGS}

else

    ${CXX} -fPIC -shared -o $PREFIX/lib/libhealpix_cxx.so -Wl,--whole-archive $PREFIX/lib/libsharp.a $PREFIX/lib/libhealpix_cxx.a -Wl,--no-whole-archive ${CXXFLAGS} ${LDFLAGS}

fi
```

2022-01-05 17:14 UTC, mwittgen commented
The result of the new build recipe for 3.31 are shared and static libs. Just deleting 
the static libs after relinking to shared in 3.80 is a slightly different product.
I am not sure how healpix_cxx is actually used by the conda-forge community, but the 
current package is of limited usability due to the missing shlib. Really playing it safe could is the build 
a new variant of 3.31 and have the users pick to use the old 3.31 or the new variant.

2022-01-05 17:19 UTC, beckermr requested changes
The static libs should never have been in this package in the first place. See our policy on this in the CFEP repo. People using the static libs from conda-forge are relying on an unsupported and brittle feature. 

I don't use this package and am only here as a core dev trying to help keep this package consistent with the rest of the community. 

There are two issues:

1. We need to separate the static libs into another package or delete them. 
2. We cannot vendor shared libs from other libs here. We attempted to fix this in the 3.80 build.

2022-01-05 17:25 UTC, mwittgen commented
OK. This can be fixed. But this would break any current usage of healpix_cxx.
There is no other lib currently in the package

> The static libs should never have been in this package in the first place. See our policy on this in the CFEP repo. People using the static libs from conda-forge are relying on an unsupported and brittle feature.
> 
> I don't use this package and am only here as a core dev trying to help keep this package consistent with the rest of the community.
> 
> There are two issues:
> 
> 1. We need to separate the static libs into another package or delete them.
Easy fix, adding a delete
> 2. We cannot vendor shared libs from other libs here. We attempted to fix this in the 3.80 build.
The package would only vendor libhealpix_cxx.

2022-01-05 17:27 UTC, beckermr commented
> OK. This can be fixed. But this would break any current usage of healpix_cxx.
> There is no other lib currently in the package

Breakage is fine here. We are free to break unsupported behavior.

2022-01-05 17:28 UTC, mwittgen commented
Probably moving forward to 3.80 is a good idea after fixing 3.31

2022-01-05 17:33 UTC, beckermr commented
If you have specific downstream code that builds against these shared libs, testing it against the libs in the 3.80 or this PR would be great. We are trying to bundle some stuff together and that might not be working how we thing it is.

2022-01-05 22:25 UTC, mwittgen commented
Simplified the recipe. Only the shlib version is built, all test programs are dynamically linked.

2022-01-06 12:01 UTC, beckermr commented on recipe/meta.yaml
>  build:
We need a run export here.

2022-01-06 22:31 UTC, beckermr commented on recipe/meta.yaml
>  build:
```suggestion
build:
  run_exports:
    - {{ pin_subpackage("healpix_cxx", max_pin="x.x") }}
```

2022-01-07 14:34 UTC, beckermr approved these changes

2022-01-07 14:35 UTC, merged